<template>
  <div class="loading" :class="{show:isLoading }" >
    <div class="loadingio-spinner-rolling-xqx1c1704ej">
      <div class="ldio-p8je1gaehq">
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "loading",
  props: {
    isLoading: Boolean,
  },
};
</script>

<style>
.loading{
    position: fixed;
    top:0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0,0,0,0.6);
    transition: all .3s ease;
    /* display: none; */
    opacity: 0;
    visibility: hidden;
    z-index: 100000;
} 
.loading.show{
    /* display: unset; */
    opacity: 0.5;
    visibility: visible;
}
.loading .loadingio-spinner-rolling-xqx1c1704ej{
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
}

@keyframes ldio-p8je1gaehq {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-p8je1gaehq div {
  position: absolute;
  width: 70.19999999999999px;
  height: 70.19999999999999px;
  border: 11.7px solid #e15b64;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-p8je1gaehq div {
  animation: ldio-p8je1gaehq 1.2195121951219512s linear infinite;
  top: 58.5px;
  left: 58.5px;
}
.loadingio-spinner-rolling-xqx1c1704ej {
  width: 117px;
  height: 117px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-p8je1gaehq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-p8je1gaehq div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>